name: BUILD_C
on:
  workflow_dispatch:

    inputs:
      name:
        description: Name of directory
        required: true
        default: Windows

jobs:
  test:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - name: vss
        shell: cmd
        run: |
          wmic cpu get /value
          vssadmin.exe create shadow /for=c:
          source-list.cmd "C:\${{ inputs.name }}\"
          
      - name: Download and Extract wimlib
        run: |
          dir \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy1\
          Invoke-WebRequest -Uri 'https://wimlib.net/downloads/wimlib-1.13.6-windows-x86_64-bin.zip' -OutFile wimlib.zip
          Expand-Archive wimlib.zip -DestinationPath .\
      - name: capture
        shell: cmd
        run: |          
          .\wimlib-imagex.exe capture --source-list source-list.txt "c:\temp\${{ inputs.name }}.wim" 
          vssadmin delete shadows /all /quiet
          dir "c:\temp\${{ inputs.name }}.wim"
      - uses: actions/upload-artifact@v3
        with:
          name: "${{ inputs.name }}.wim"
          path: c:\temp\${{ inputs.name }}.wim
