name: build_c
on:
  workflow_dispatch:

    inputs:
      name:
        description: Name of directory
        required: false
      filesonly:
        description: filesonly
        required: true
        default: A

run-name: ${{ inputs.name }}

jobs:
  test:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v3
      - name: vss
        shell: cmd
        run: |
          wmic cpu get /value
          vssadmin.exe create shadow /for=c:
          
          
      - name: Download and Extract wimlib
        run: |
          Invoke-WebRequest -Uri 'https://wimlib.net/downloads/wimlib-1.13.6-windows-x86_64-bin.zip' -OutFile wimlib.zip
          Expand-Archive wimlib.zip -DestinationPath .\
          "fixed_name=${{ inputs.name }}" -replace '\\', '_' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: create source-list.txt
        shell: cmd
        run: echo source-list.cmd "C:\${{ inputs.name }}" ${{ inputs.filesonly }} > source-list.txt 
      - name: echo env
        shell: cmd
        run: |
          type source-list.txt
          echo "${{ env.fixed_name }}"
          echo "${{ inputs.name }}"
        
      - name: update source-list.txt
        shell: cmd
        if: github.event.inputs.filesonly == 'A'
        run: echo "\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy1\${{ inputs.name }}\" "\${{ inputs.name }}" > source-list.txt
         
      - name: echo env2
        shell: cmd
        run: |
          type source-list.txt
          echo "${{ env.fixed_name }}"
          echo "${{ inputs.name }}"
        
      - name: capture
        shell: cmd
        run: wimlib-imagex.exe capture --source-list source-list.txt "c:\temp\win_${{ env.fixed_name }}.wim" --compress=lzms

      - name: clean vss
        shell: cmd
        run: vssadmin delete shadows /all /quiet
        
      - name: clean vss
        shell: cmd
        run: dir "c:\temp\win_${{ env.fixed_name }}.wim"

      - uses: actions/upload-artifact@v3
        with:
          name: "win_${{ env.fixed_name }}.wim"
          path: c:\temp\win_${{ env.fixed_name }}.wim
