name: BUILD_C
on:
  workflow_dispatch:

    inputs:
      name:
        description: Name of directory
        required: false
      recursive:
        description: resurcive directory
        required: true
        default: Yes

jobs:
  test:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - name: vss
        shell: cmd
        run: |
          wmic cpu get /value
          vssadmin.exe create shadow /for=c:
          
          
      - name: Download and Extract wimlib
        run: |
          Invoke-WebRequest -Uri 'https://wimlib.net/downloads/wimlib-1.13.6-windows-x86_64-bin.zip' -OutFile wimlib.zip
          Expand-Archive wimlib.zip -DestinationPath .\
          "fixed_name=${{ inputs.name }}" -replace '\\', '_' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: create source-list.txt
        shell: cmd
        run: source-list.cmd "C:\${{ inputs.name }}" ${{ inputs.recursive }} > source-list.txt 
      - name: echo env
        shell: cmd
        run: |
          type source-list.txt
          echo "${{ env.fixed_name }}"
          echo "${{ inputs.name }}"
        
      - name: capture_full
        if: ${{${{ inputs.recursive }} == "Yes"}}
        shell: cmd
        run: |
          .\wimlib-imagex.exe capture "\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy1\${{ inputs.name }}" "c:\temp\win_${{ env.fixed_name }}.wim" --compress=recovery
          vssadmin delete shadows /all /quiet
          dir "c:\temp\win_${{ env.fixed_name }}.wim"

      - name: capture_only_files
        if: ${{${{ inputs.recursive }} != "Yes"}}
        shell: cmd
        run: |
          .\wimlib-imagex.exe capture --source-list source-list.txt "c:\temp\win_${{ env.fixed_name }}.wim" --compress=recovery
          vssadmin delete shadows /all /quiet
          dir "c:\temp\win_${{ env.fixed_name }}.wim"

      - uses: actions/upload-artifact@v3
        with:
          name: "win_${{ env.fixed_name }}.wim"
          path: c:\temp\win_${{ env.fixed_name }}.wim
